### ISSUE TITLE
Possible to install parts

### ISSUE THREAD

**Issue by jerone** [skratchdot/github-enhancement-suite#2]
I had [GitHub Repo Counts](https://github.com/skratchdot/github-repo-counts.user.js) installed, when I noticed that it's now moved to this enhancement suite. I prefer to only use that one feature, as I don't want other features or have [my own userscripts](https://github.com/jerone/UserScripts#github) for that. Is it possible to install only repo counts or disable other parts?

**Comment by skratchdot** [comment]
@jerone - not yet.  I guess I could make it work that way.  If you install the whole suite, you can go to the /settings/profile page and turn off all the other features (and it will still be lightweight).

I'm working on updating the documentation still, and adding screenshots, but won't get to it today.

I'll think about still having the scripts install-able by themselves, but don't want it to be a maintenance nightmare for me.  I should be able to do it though...

Can you try installing the whole suite, and seeing if turning off all the other features works for you?  I've had to decommission a few of the scripts that no longer make sense.  In the coming weeks I plan on adding some nice new features...

**Comment by skratchdot** [comment]
@jerone - After looking at this, and thinking about it a bit, I should be able to make each script installable by itself.  I'll try to get to it when I get a bit of free time.

**Comment by jerone** [comment]
[**@skratchdot**](https://github.com/skratchdot) commented on [2 sep. 2015 22:42 CEST](https://github.com/skratchdot/github-enhancement-suite/issues/2#issuecomment-137238342):

> [@jerone](https://github.com/jerone) - After looking at this, and thinking about it a bit, I should be able to make each script installable by itself.  I'll try to get to it when I get a bit of free time.

That would be perfect! :+1:

**Comment by jerone** [comment]
> If you install the whole suite, you can go to the /settings/profile page and turn off all the other features

Didn't know that. Aldo possibility to install separate userscripts would be perfect (works better when sync is enabled with other environments), enabling/disabling parts of the suite in settings/profile works great too. Probably good idea to put this in the documentation.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
